FROM debian:latest

MAINTAINER henry@stored.cc

RUN apt-get update && apt-get install -y wget
RUN wget {{thanos_dl_url}} -O /thanos.tar.gz
RUN cd / && tar -xvf thanos.tar.gz
RUN cd / && mv /thanos-*/thanos /usr/bin/thanos
RUN rm -rf /thanos*
