---
  - name: Create {{base_dir}}
    file:
      path: "{{base_dir}}"
      state: directory
      mode: '777'

  - name: Create {{base_dir}}/{{instance}}
    file:
      path: "{{base_dir}}/{{instance}}"
      state: directory
      mode: '777'

  - name: Create {{base_dir}}/{{instance}}/Thanos
    file:
      path: "{{base_dir}}/{{instance}}/Thanos"
      state: directory
      mode: '777'

  - name: Template {{base_dir}}/{{instance}}/Thanos/Dockerfile
    template:
      src: templates/Thanos/Dockerfile.j2
      dest: "{{base_dir}}/{{instance}}/Thanos/Dockerfile"
      owner: root
      group: root
      mode: 0744

  - name: Template {{base_dir}}/{{instance}}/minio.config.json
    template:
      src: templates/minio/config.json.j2
      dest: "{{base_dir}}/{{instance}}/minio.config.json"
      owner: root
      group: root
      mode: 0744

  - name: Template {{base_dir}}/{{instance}}/docker-compose.yml
    template:
      src: templates/docker-compose.yml.j2
      dest: "{{base_dir}}/{{instance}}/docker-compose.yml"
      owner: root
      group: root
      mode: 0744

  - name: Template {{base_dir}}/{{instance}}/s3.yml
    template:
      src: templates/s3.yml.j2
      dest: "{{base_dir}}/{{instance}}/s3.yml"
      owner: root
      group: root
      mode: 0744


  - name: Exec docker-compose up -d {{base_dir}}/{{instance}}
    shell: cd {{base_dir}}/{{instance}} && docker-compose up -d

