---

#Thanos global configs
minio_url: stored.cc #Enter your public facing ip / hostname here
minio_port: 9000 #Port should be self explanatory
minio_access_key: xxxxxxxxxxxx
minio_secret_key: xxxxxx+xxxxxxxxxxxxx
base_dir: '/opt'

#We build our Docker Images ourselfes here
thanos_dl_url: 'https://github.com/thanos-io/thanos/releases/download/v0.6.0/thanos-0.6.0.linux-amd64.tar.gz'
prometheus_dl_url: 'https://github.com/prometheus/prometheus/releases/download/v2.11.1/prometheus-2.11.1.linux-amd64.tar.gz'

#some temporary variables, which are filled by the ansible run. We need them later to create the missing buckets and add the --store parameters
store: ""
buckets: ""
